# Generated by Django 4.2.4 on 2023-08-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="track_id",
            new_name="pay_id",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("CANCELLED", "CANCELLED"),
                    ("CONFIRMED", "CONFIRMED"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
