# Generated by Django 4.2.4 on 2023-08-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="pay_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
