# Generated by Django 4.2.4 on 2023-08-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="pay_link",
        ),
        migrations.AddField(
            model_name="user",
            name="pay_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
