# Generated by Django 4.2.3 on 2023-08-01 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("cc", models.CharField(max_length=16)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("cvv", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zip", models.IntegerField()),
                ("country", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("ssn", models.CharField(blank=True, max_length=255, null=True)),
                ("DOB", models.DateField(blank=True, null=True)),
                ("price", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dumps",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("bin", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                (
                    "cc_type",
                    models.CharField(
                        choices=[
                            ("Visa", "Visa"),
                            ("Mastercard", "Mastercard"),
                            ("Amex", "Amex"),
                            ("Discover", "Discover"),
                            ("JCB", "JCB"),
                            ("Diners Club", "Diners Club"),
                        ],
                        max_length=255,
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("bank", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "Dumps",
            },
        ),
        migrations.CreateModel(
            name="Fullz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("DOB", models.DateField(blank=True, null=True)),
                ("category", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("zip", models.IntegerField()),
                ("description", models.TextField()),
                ("price", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Guides",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("extra", models.TextField()),
                ("price", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "Guides",
            },
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("extra", models.TextField()),
                ("price", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "Logs",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "News",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("extra", models.TextField()),
                ("price", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="CartProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("product", models.CharField(max_length=64)),
                ("product_id", models.PositiveBigIntegerField()),
                (
                    "cc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.cc",
                    ),
                ),
                (
                    "fullz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.fullz",
                    ),
                ),
                (
                    "guides",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.guides",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
