# Generated by Django 4.2.4 on 2023-08-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cc",
            name="cc_type",
            field=models.CharField(
                choices=[
                    ("Visa", "Visa"),
                    ("Mastercard", "Mastercard"),
                    ("Amex", "Amex"),
                    ("Discover", "Discover"),
                    ("JCB", "JCB"),
                    ("Diners Club", "Diners Club"),
                ],
                default="Visa",
                max_length=255,
            ),
        ),
    ]
