# Generated by Django 4.2.3 on 2023-08-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartproduct",
            name="cc",
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="fullz",
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="guides",
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="product_id",
            field=models.UUIDField(),
        ),
    ]
