# Generated by Django 4.2.3 on 2023-07-31 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_cc_alter_news_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cc",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
