# Generated by Django 4.2.4 on 2023-08-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_cc_cc_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cc",
            name="zip",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="fullz",
            name="zip",
            field=models.CharField(max_length=10),
        ),
    ]
