# Generated by Django 4.2.3 on 2023-07-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_cc_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="cc",
            name="cc",
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
