# Generated by Django 4.2.4 on 2023-08-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_cc_delivered_to_dumps_delivered_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cc",
            name="extra",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dumps",
            name="extra",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fullz",
            name="extra",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guides",
            name="extra",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="logs",
            name="extra",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="services",
            name="extra",
            field=models.TextField(blank=True, null=True),
        ),
    ]
