# Generated by Django 4.2.3 on 2023-07-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_cc_cc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cc",
            name="cvv",
            field=models.IntegerField(),
        ),
    ]
