# Generated by Django 4.2.3 on 2023-07-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_cc_cvv"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fullz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("DOB", models.DateField(blank=True, null=True)),
                ("category", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("zip", models.IntegerField()),
                ("description", models.TextField()),
                ("price", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
