# Generated by Django 4.2.3 on 2023-08-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_fullz"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dumps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("bin", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                (
                    "cc_type",
                    models.CharField(
                        choices=[
                            ("Visa", "Visa"),
                            ("Mastercard", "Mastercard"),
                            ("Amex", "Amex"),
                            ("Discover", "Discover"),
                            ("JCB", "JCB"),
                            ("Diners Club", "Diners Club"),
                        ],
                        max_length=255,
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("bank", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Guides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("extra", models.TextField()),
                ("price", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("extra", models.TextField()),
                ("price", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("extra", models.TextField()),
                ("price", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
